### ISSUE TITLE
How is this project run? 

### ISSUE THREAD

**Issue by omrihq** [pbvie/hello-grpc#14]
Trying to compile/run a combo of server/client w/o much luck 
After running `sbt run` in `hello-grpc/`, I get prompted with 

```
Multiple main classes detected, select one to run:

 [1] io.ontherocks.hellogrpc.clock.ClockClientApp
 [2] io.ontherocks.hellogrpc.clock.ClockServerApp
 [3] io.ontherocks.hellogrpc.sum.SumClientApp
 [4] io.ontherocks.hellogrpc.sum.SumServerApp
```

and after selecting the SumServerApp I get:

```[info] Running io.ontherocks.hellogrpc.sum.SumServerApp 
[error] (run-main-0) java.io.IOException: Failed to bind
java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:158)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:161)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:83)
	at io.ontherocks.hellogrpc.server.HelloGrpcServer.start(HelloGrpcServer.scala:36)```

**Comment by omrihq** [comment]
Closed, wasn't familiar with the `BindException` error, didn't realize I had an unrelated test server already running on the same port
